<?php
/**
 * arbit autoload file
 *
 * This file is part of arbit.
 *
 * arbit is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 3 of the License.
 *
 * arbit is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with arbit; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package Core
 * @version $Revision: 962 $
 * @license http://www.gnu.org/licenses/gpl-3.0.txt GPL
 */

/*
 * This array is autogenerated and topoligically sorted. Do not change anything
 * in here, but just run the following script in the trunk/ directory.
 *
 * # scripts/gen_autoload_files.php
 */
return array(
    'periodicCronjob'                 => 'cronjob.php',
    'periodicCronjobIterator'         => 'cronjobIterator.php',
    'periodicException'               => 'exceptions.php',
    'periodicAttributeException'      => 'exceptions.php',
    'periodicInvalidCronjobException' => 'exceptions.php',
    'arbitXmlNode'                    => 'external/xml/node.php',
    'arbitCacheable'                  => 'external/xml/cacheable.php',
    'arbitXml'                        => 'external/xml/document.php',
    'arbitException'                  => 'external/xml/exceptions.php',
    'arbitNoSuchFileException'        => 'external/xml/exceptions.php',
    'arbitXmlParserException'         => 'external/xml/exceptions.php',
    'arbitAccessException'            => 'external/xml/exceptions.php',
    'arbitValueException'             => 'external/xml/exceptions.php',
    'arbitXmlNodeList'                => 'external/xml/node_list.php',
);

