<?php
/**
 * Autoload file
 *
 * This file is part of periodic
 *
 * periodic is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; version 3 of the License.
 *
 * periodic is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with periodic; if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @package Core
 * @version $Revision: 977 $
 * @license http://www.gnu.org/licenses/lgpl-3.0.txt LGPL
 */

/*
 * This array is autogenerated and topoligically sorted. Do not change anything
 * in here, but just run the following script:
 *
 * # scripts/gen_autoload_files.php
 */
return array(
    'periodicCommand'                 => 'command.php',
    'periodicCommandRegistry'         => 'command_registry.php',
    'periodicCronjob'                 => 'cronjob.php',
    'periodicCronjobIterator'         => 'cronjob_iterator.php',
    'periodicException'               => 'exceptions.php',
    'periodicAttributeException'      => 'exceptions.php',
    'periodicInvalidCronjobException' => 'exceptions.php',
    'periodicExecutor'                => 'executor.php',
    'arbitXmlNode'                    => 'external/xml/node.php',
    'arbitCacheable'                  => 'external/xml/cacheable.php',
    'arbitXml'                        => 'external/xml/document.php',
    'arbitException'                  => 'external/xml/exceptions.php',
    'arbitNoSuchFileException'        => 'external/xml/exceptions.php',
    'arbitXmlParserException'         => 'external/xml/exceptions.php',
    'arbitAccessException'            => 'external/xml/exceptions.php',
    'arbitValueException'             => 'external/xml/exceptions.php',
    'arbitXmlNodeList'                => 'external/xml/node_list.php',
    'periodicLogger'                  => 'logger.php',
    'periodicTask'                    => 'task.php',
    'periodicTaskFactory'             => 'task_factory.php',
);

